-- MySQL Script generated by MySQL Workbench
-- Sat Dec  7 14:33:12 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema GoT_Hospital_OPC
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema GoT_Hospital_OPC
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `GoT_Hospital_OPC` DEFAULT CHARACTER SET utf8 ;
USE `GoT_Hospital_OPC` ;

-- -----------------------------------------------------
-- Table `GoT_Hospital_OPC`.`Insurance_Company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GoT_Hospital_OPC`.`Insurance_Company` ;

CREATE TABLE IF NOT EXISTS `GoT_Hospital_OPC`.`Insurance_Company` (
  `Insurace_Company_ID` INT NOT NULL AUTO_INCREMENT,
  `Insuranceprovider_Name` VARCHAR(45) NOT NULL,
  `InsuranceProvider_Location` VARCHAR(50) NULL,
  `InsuranceProvider_Contact` VARCHAR(45) NULL,
  `InsuranceProvider_Email` VARCHAR(45) NULL,
  PRIMARY KEY (`Insurace_Company_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GoT_Hospital_OPC`.`Patients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GoT_Hospital_OPC`.`Patients` ;

CREATE TABLE IF NOT EXISTS `GoT_Hospital_OPC`.`Patients` (
  `Patient_ID` INT NOT NULL AUTO_INCREMENT,
  `Insurace_Company_ID` INT NOT NULL,
  `Patient_firstName` VARCHAR(45) NULL,
  `Patient_LastName` VARCHAR(45) NULL,
  `Patient_DOB` DATE NULL,
  `Gender` VARCHAR(45) NOT NULL,
  `PatientInsurance_ID` INT NOT NULL,
  `Insurance_ExpiryDate` DATE NULL,
  PRIMARY KEY (`Patient_ID`),
  CONSTRAINT `Patients_fk_Insurance_Company`
    FOREIGN KEY (`Insurace_Company_ID`)
    REFERENCES `GoT_Hospital_OPC`.`Insurance_Company` (`Insurace_Company_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `LASTNAME_INDEX` ON `GoT_Hospital_OPC`.`Patients` (`Patient_LastName` ASC) INVISIBLE;

CREATE INDEX `Patients_fk_Insurance_Company_idx` ON `GoT_Hospital_OPC`.`Patients` (`Insurace_Company_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `GoT_Hospital_OPC`.`Speciality`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GoT_Hospital_OPC`.`Speciality` ;

CREATE TABLE IF NOT EXISTS `GoT_Hospital_OPC`.`Speciality` (
  `Speciality_ID` INT NOT NULL AUTO_INCREMENT,
  `Speciality_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Speciality_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GoT_Hospital_OPC`.`Doctors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GoT_Hospital_OPC`.`Doctors` ;

CREATE TABLE IF NOT EXISTS `GoT_Hospital_OPC`.`Doctors` (
  `Doctor_ID` INT NOT NULL AUTO_INCREMENT,
  `Speciality_ID` INT NOT NULL,
  `Doctor_FirstName` VARCHAR(45) NULL,
  `Doctor_LastName` VARCHAR(45) NULL,
  `Doctor_Phone` VARCHAR(45) NOT NULL,
  `Doctor_Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Doctor_ID`),
  CONSTRAINT `Doctors_fk_Speciality`
    FOREIGN KEY (`Speciality_ID`)
    REFERENCES `GoT_Hospital_OPC`.`Speciality` (`Speciality_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `Doctor_LastName_idx` ON `GoT_Hospital_OPC`.`Doctors` (`Doctor_LastName` ASC) VISIBLE;

CREATE INDEX `Doctors_fk_Speciality_idx` ON `GoT_Hospital_OPC`.`Doctors` (`Speciality_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `GoT_Hospital_OPC`.`Visits`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GoT_Hospital_OPC`.`Visits` ;

CREATE TABLE IF NOT EXISTS `GoT_Hospital_OPC`.`Visits` (
  `Visit_ID` INT NOT NULL AUTO_INCREMENT,
  `Patient_ID` INT NOT NULL,
  `Doctor_ID` INT NOT NULL,
  `Facility` VARCHAR(60) NULL,
  `Visit_TimeIN` DATETIME NULL,
  `Visit_TimeOUT` DATETIME NULL,
  PRIMARY KEY (`Visit_ID`),
  CONSTRAINT `Visits_fk_Patients`
    FOREIGN KEY (`Patient_ID`)
    REFERENCES `GoT_Hospital_OPC`.`Patients` (`Patient_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Visits_fk_Doctors`
    FOREIGN KEY (`Doctor_ID`)
    REFERENCES `GoT_Hospital_OPC`.`Doctors` (`Doctor_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `DATEINDEX` ON `GoT_Hospital_OPC`.`Visits` (`Visit_TimeIN` ASC) VISIBLE;

CREATE INDEX `Visits_fk_Doctors_idx` ON `GoT_Hospital_OPC`.`Visits` (`Doctor_ID` ASC) VISIBLE;

CREATE INDEX `Visits_fk_Patients_idx` ON `GoT_Hospital_OPC`.`Visits` (`Patient_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `GoT_Hospital_OPC`.`Diagnosis`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GoT_Hospital_OPC`.`Diagnosis` ;

CREATE TABLE IF NOT EXISTS `GoT_Hospital_OPC`.`Diagnosis` (
  `Diagnosis_ID` INT NOT NULL AUTO_INCREMENT,
  `Visit_ID` INT NOT NULL,
  `Diagnosis_Description` VARCHAR(1000) NULL,
  PRIMARY KEY (`Diagnosis_ID`),
  CONSTRAINT `Diagnosis_fk_Visits`
    FOREIGN KEY (`Visit_ID`)
    REFERENCES `GoT_Hospital_OPC`.`Visits` (`Visit_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `Diagnosis_Description_idx` ON `GoT_Hospital_OPC`.`Diagnosis` (`Diagnosis_Description` ASC) VISIBLE;

CREATE INDEX `Diagnosis_fk_Visits_idx` ON `GoT_Hospital_OPC`.`Diagnosis` (`Visit_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `GoT_Hospital_OPC`.`Symptom_Sheet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GoT_Hospital_OPC`.`Symptom_Sheet` ;

CREATE TABLE IF NOT EXISTS `GoT_Hospital_OPC`.`Symptom_Sheet` (
  `Symptom_Sheet_ID` INT NOT NULL AUTO_INCREMENT,
  `Visit_ID` INT NOT NULL,
  `Symptom_Name` VARCHAR(200) NULL,
  `Symptom_Description` VARCHAR(500) NULL,
  `Days_effected` INT NULL,
  `Symptoms_Severity` VARCHAR(45) NULL,
  PRIMARY KEY (`Symptom_Sheet_ID`),
  CONSTRAINT `Symptom_Sheet_fk_Visits`
    FOREIGN KEY (`Visit_ID`)
    REFERENCES `GoT_Hospital_OPC`.`Visits` (`Visit_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `Symptom_Name_idx` ON `GoT_Hospital_OPC`.`Symptom_Sheet` (`Symptom_Name` ASC) INVISIBLE;


-- -----------------------------------------------------
-- Table `GoT_Hospital_OPC`.`Prescription`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GoT_Hospital_OPC`.`Prescription` ;

CREATE TABLE IF NOT EXISTS `GoT_Hospital_OPC`.`Prescription` (
  `Prescription_ID` INT NOT NULL AUTO_INCREMENT,
  `Visit_ID` INT NOT NULL,
  `Medication_Description` VARCHAR(200) NULL,
  `Medication_Quantity` INT NULL,
  `Medication_Dosage` VARCHAR(45) NULL,
  PRIMARY KEY (`Prescription_ID`),
  CONSTRAINT `Prescription_fk_Visits`
    FOREIGN KEY (`Visit_ID`)
    REFERENCES `GoT_Hospital_OPC`.`Visits` (`Visit_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `Prescription_fk_Visits_idx` ON `GoT_Hospital_OPC`.`Prescription` (`Visit_ID` ASC) VISIBLE;

CREATE UNIQUE INDEX `Visit_ID_UNIQUE` ON `GoT_Hospital_OPC`.`Prescription` (`Visit_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `GoT_Hospital_OPC`.`Billing`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GoT_Hospital_OPC`.`Billing` ;

CREATE TABLE IF NOT EXISTS `GoT_Hospital_OPC`.`Billing` (
  `Bill_ID` INT NOT NULL AUTO_INCREMENT,
  `Visit_ID` INT NOT NULL,
  `Total_Bill` DECIMAL(10,2) NULL,
  `Insurance_Amount` DECIMAL(10,2) NULL,
  `Balance_Due` DECIMAL(10,2) NULL,
  `Billing_Description` VARCHAR(45) NULL,
  PRIMARY KEY (`Bill_ID`),
  CONSTRAINT `Billing_fk_Visits`
    FOREIGN KEY (`Visit_ID`)
    REFERENCES `GoT_Hospital_OPC`.`Visits` (`Visit_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `Billing_fk_Visits_idx` ON `GoT_Hospital_OPC`.`Billing` (`Visit_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `GoT_Hospital_OPC`.`Contact_Details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GoT_Hospital_OPC`.`Contact_Details` ;

CREATE TABLE IF NOT EXISTS `GoT_Hospital_OPC`.`Contact_Details` (
  `Patient_ID` INT NOT NULL AUTO_INCREMENT,
  `Address_Line1` VARCHAR(45) NULL,
  `Address_Line2` VARCHAR(45) NULL,
  `Patient_Phn` VARCHAR(45) NOT NULL,
  `Patient_Email` VARCHAR(45) NOT NULL,
  `State` VARCHAR(45) NOT NULL,
  `City` VARCHAR(45) NOT NULL,
  `Zip_Code` INT NOT NULL,
  PRIMARY KEY (`Patient_ID`),
  CONSTRAINT `Patient_Contacts_FK`
    FOREIGN KEY (`Patient_ID`)
    REFERENCES `GoT_Hospital_OPC`.`Patients` (`Patient_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GoT_Hospital_OPC`.`Tests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GoT_Hospital_OPC`.`Tests` ;

CREATE TABLE IF NOT EXISTS `GoT_Hospital_OPC`.`Tests` (
  `Test_ID` INT NOT NULL AUTO_INCREMENT,
  `Diagnosis_ID` INT NOT NULL,
  `Test_Name` VARCHAR(45) NULL,
  `Test_Result` VARCHAR(45) NULL,
  PRIMARY KEY (`Test_ID`),
  CONSTRAINT `Diagnosis_id`
    FOREIGN KEY (`Diagnosis_ID`)
    REFERENCES `GoT_Hospital_OPC`.`Diagnosis` (`Diagnosis_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `Test_Name_idx` ON `GoT_Hospital_OPC`.`Tests` (`Test_Name` ASC) INVISIBLE;


-- -----------------------------------------------------
-- Table `GoT_Hospital_OPC`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GoT_Hospital_OPC`.`Users` ;

CREATE TABLE IF NOT EXISTS `GoT_Hospital_OPC`.`Users` (
  `UserName` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Role` VARCHAR(45) NULL,
  PRIMARY KEY (`UserName`, `Password`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GoT_Hospital_OPC`.`Patients_audit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GoT_Hospital_OPC`.`Patients_audit` ;

CREATE TABLE IF NOT EXISTS `GoT_Hospital_OPC`.`Patients_audit` (
  `Patients_auditID` INT NOT NULL AUTO_INCREMENT,
  `Patient_ID` INT NULL,
  `Insurace_Company_ID` INT NULL,
  `Patient_firstName` VARCHAR(45) NULL,
  `Patient_LastName` VARCHAR(45) NULL,
  `Patient_DOB` DATE NULL,
  `Gender` VARCHAR(45) NULL,
  `PatientInsurance_ID` INT NULL,
  `Insurance_ExpiryDate` DATE NULL,
  `action_type` VARCHAR(45) NULL,
  `action_date` DATETIME NULL,
  `UserName` VARCHAR(45) NULL,
  PRIMARY KEY (`Patients_auditID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GoT_Hospital_OPC`.`Billing_audit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GoT_Hospital_OPC`.`Billing_audit` ;

CREATE TABLE IF NOT EXISTS `GoT_Hospital_OPC`.`Billing_audit` (
  `Billing_auditID` INT NOT NULL AUTO_INCREMENT,
  `Bill_ID` INT NULL,
  `Visit_ID` INT NULL,
  `Total_Bill` DECIMAL(10,2) NULL,
  `Insurance_Amount` DECIMAL(10,2) NULL,
  `Balance_Due` DECIMAL(10,2) NULL,
  `Billing_Description` VARCHAR(45) NULL,
  `action_type` VARCHAR(45) NULL,
  `action_date` DATETIME NULL,
  `UserName` VARCHAR(45) NULL,
  PRIMARY KEY (`Billing_auditID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GoT_Hospital_OPC`.`Diagnosis_audit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GoT_Hospital_OPC`.`Diagnosis_audit` ;

CREATE TABLE IF NOT EXISTS `GoT_Hospital_OPC`.`Diagnosis_audit` (
  `Diagnosis_auditID` INT NOT NULL AUTO_INCREMENT,
  `Diagnosis_ID` INT NULL,
  `Visit_ID` INT NULL,
  `Diagnosis_Description` VARCHAR(1000) NULL,
  `action_type` VARCHAR(45) NULL,
  `action_date` DATETIME NULL,
  `UserName` VARCHAR(45) NULL,
  PRIMARY KEY (`Diagnosis_auditID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GoT_Hospital_OPC`.`visit_audit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GoT_Hospital_OPC`.`visit_audit` ;

CREATE TABLE IF NOT EXISTS `GoT_Hospital_OPC`.`visit_audit` (
  `visit_auditID` INT NOT NULL AUTO_INCREMENT,
  `Visit_ID` INT NULL,
  `Patient_ID` INT NULL,
  `Doctor_ID` INT NULL,
  `Facility` VARCHAR(60) NULL,
  `Visit_TimeIN` DATETIME NULL,
  `Visit_TimeOUT` DATETIME NULL,
  `action_type` VARCHAR(45) NULL,
  `action_date` DATETIME NULL,
  `UserName` VARCHAR(45) NULL,
  PRIMARY KEY (`visit_auditID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
